// <auto-generated />
using System;
using GoSportsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoSportsAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20251105094131_AddVersions")]
    partial class AddVersions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoSportsAPI.Models.Lobbies.Lobby", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LobbyId");

                    b.HasIndex("LocationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SportId");

                    b.ToTable("lobbies");
                });

            modelBuilder.Entity("GoSportsAPI.Models.Locations.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentLobbyCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MaxLobbyCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("LocationId");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("GoSportsAPI.Models.Locations.LocationType", b =>
                {
                    b.Property<Guid>("LocationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasLights")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationTypeId");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("locationTypes");
                });

            modelBuilder.Entity("GoSportsAPI.Models.Sports.Sport", b =>
                {
                    b.Property<Guid>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SportId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("sports");
                });

            modelBuilder.Entity("LocationSport", b =>
                {
                    b.Property<Guid>("LocationsLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SportsSportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LocationsLocationId", "SportsSportId");

                    b.HasIndex("SportsSportId");

                    b.ToTable("LocationSports", (string)null);
                });

            modelBuilder.Entity("GoSportsAPI.Models.Lobbies.Lobby", b =>
                {
                    b.HasOne("GoSportsAPI.Models.Locations.Location", "Location")
                        .WithMany("Lobbies")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoSportsAPI.Models.Sports.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("GoSportsAPI.Models.Locations.LocationType", b =>
                {
                    b.HasOne("GoSportsAPI.Models.Locations.Location", null)
                        .WithOne("LocationType")
                        .HasForeignKey("GoSportsAPI.Models.Locations.LocationType", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocationSport", b =>
                {
                    b.HasOne("GoSportsAPI.Models.Locations.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoSportsAPI.Models.Sports.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportsSportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoSportsAPI.Models.Locations.Location", b =>
                {
                    b.Navigation("Lobbies");

                    b.Navigation("LocationType")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
